apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8SDisallowRWFilesystem
metadata:
  name: container-readonly-fs
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
